name: Build and Release Windows EXE

on:
  push:
    branches: [ "main" ]
    # با اضافه کردن بخش زیر، ورک‌فلو فقط با تغییر این دو فایل اجرا می‌شود
    paths:
      - 'deploy.py'
      - 'zeus.js'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build EXE with PyInstaller
      run: |
        # در این خط نام فایل خروجی و ورژن‌گذاری داینامیک تنظیم شده است
        pyinstaller --onefile --name="Zeus_Deployer_v1.0.${{ github.run_number }}" --icon=icon.ico --clean deploy.py
        
    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Zeus Panel Deployer v1.0.${{ github.run_number }}
        files: dist/Zeus_Deployer_v1.0.${{ github.run_number }}.exe
        draft: false
        prerelease: false
